In [3]:
import numpy as np
from scipy.stats import norm, beta
norm.cdf(1, [0,0], [1,1] )

array([0.84134475, 0.84134475])

In [2]:
import numpy as np
rewards = np.ones((5,10))
diff_rewards =  2 - rewards 
random_regrets = np.cumsum(diff_rewards, axis=1)
np.mean(random_regrets, axis=0)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [1]:
import numpy as np 
k = 10
n_agents = 3
n0 = 10
c = 0.5

social_information = n0 * np.ones((n_agents, k))
pi_TS = np.random.rand(k) 
pi_TS = pi_TS / np.sum(pi_TS)
print(pi_TS)

U = np.log(social_information/np.sum(social_information, axis = 1, keepdims = True) + 0.00001) 
print(U.shape)
Pi_star = pi_TS * np.exp((1/c) * U)
print(Pi_star.shape)
Pi_star = Pi_star / np.sum(Pi_star, axis = 1, keepdims = True)
print(Pi_star)
FE = np.sum(Pi_star * (c*np.log((Pi_star + 0.00001)/(pi_TS + 0.00001)) - U), axis = 1)
print(FE.shape)
print(FE)

[0.00289915 0.17179605 0.15863099 0.08858084 0.17406424 0.13478921
 0.0270247  0.01632541 0.11594803 0.10994136]
(3, 10)
(3, 10)
[[0.00289915 0.17179605 0.15863099 0.08858084 0.17406424 0.13478921
  0.0270247  0.01632541 0.11594803 0.10994136]
 [0.00289915 0.17179605 0.15863099 0.08858084 0.17406424 0.13478921
  0.0270247  0.01632541 0.11594803 0.10994136]
 [0.00289915 0.17179605 0.15863099 0.08858084 0.17406424 0.13478921
  0.0270247  0.01632541 0.11594803 0.10994136]]
(3,)
[2.3024851 2.3024851 2.3024851]


In [2]:
import numpy as np 
a = np.ones((2,5,10))
a

array([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [3]:
b = np.mean(a, axis =1)
b.shape

(2, 10)

In [4]:
b

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [1]:
a = {}

a['erfan'] = {}

a['erfan']['age'] = 24
a['erfan']['height'] = 180

a['arman'] = {}
a['arman']['age'] = 20
a['arman']['weight'] = 65

for key in a:
    print(key)
    for k in a[key]:
        print(k)




erfan
age
height
arman
age
weight


In [7]:
import numpy as np 
a = np.ones((2,5))
b = np.zeros((2,5))

c = a * b
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
x = np.array([1,2,4,43])

x = x / np.sum(x)
x.shape

(4,)

In [8]:
np.sum(a, axis = 1)

array([5., 5.])

In [9]:
exp_best = 2
rewards = np.ones((1,10))
diff_rewards =  exp_best - rewards 
diff_rewards.shape, diff_rewards

((1, 10), array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]))